INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ('頭痛', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ( '吐き気', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ( '耳の違和感', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ( 'めまい、ふらつき', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ( '右首痛', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO daily_health_detail_template(NAME, DELETED, CREATED_DATE, MODIFIED_DATE) VALUES ( '左首痛', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
